export const USER_ERROR = 'USER_ERROR';
export const USER_DELETE = 'USER_DELETE';
export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_UPDATE_DETAILS = 'USER_UPDATE_DETAILS';
export const USER_UPDATE_PASSWORD = 'USER_UPDATE_PASSWORD';
export const USER_UPDATE_INTEREST = 'USER_UPDATE_INTEREST';
